### ISSUE TITLE
генерация файлов

### ISSUE THREAD

**Issue by MasterDimmy** [vodolaz095/go-investAPI#1]
День добрый.
<Здесь был глупый вопрос>

**Comment by MasterDimmy** [comment]
отбой.

**Comment by vodolaz095** [comment]
ответ на вопрос "куда?" - https://github.com/vodolaz095/go-investAPI/tree/master/investapi
ответ на вопрос "как?" - https://github.com/vodolaz095/go-investAPI/blob/master/entrypoint.sh

Надеюсь помог :-)
