### ISSUE TITLE
вопросы

### ISSUE THREAD

**Issue by MasterDimmy** [vodolaz095/go-investAPI#2]
По теме и чуть вне.
1. В песочнице стопов нет?
2. client.StopOrdersServiceClient.PostStopOrder всегда может иметь тип StopOrderType_STOP_ORDER_TYPE_STOP_LOSS или же, если цена указана выше цены покупки (но ниже текущей рыночной цены), то обязательно менять тип на StopOrderType_STOP_ORDER_TYPE_TAKE_PROFIT ?
3. TP+SL одной заявкой - нет?
4. Вне торгового времени (ночью), принимает рынок заявки?
5. При регистрации на подписку свечек выставлен SubscriptionInterval_SUBSCRIPTION_INTERVAL_ONE_MINUTE , однако свечи приходят каждые 1-10 секунд вместо 1 минуты - это фича или баг?

**Comment by vodolaz095** [comment]
1,2,3,5 - это лучше спросить у представителей банка в, как я понял, официальном репозитории с документацией 
https://github.com/Tinkoff/investAPI

4. Московская биржа не принимает, Петербургская до часа ночи по Москве принимает заявки

Я сомневаюсь, что смогу корректно ответить на Ваши вопросы.
Я просто сгенерировал Golang клиент как есть из официальных *.proto файлов, и то, что я использую, у меня работает.

На реальном счёте у меня работают стаканы, лимитные заявки, получение котировок по FIGI и аналитика (календарь инвестора, события, обзор портфеля), этого мне пока хватает.

**Comment by vodolaz095** [comment]
https://tinkoff.github.io/investAPI/head-sandbox/

как я понял, стопы в песочнице сразу срабатыают

**Comment by vodolaz095** [comment]
2. не совсем это понял из документации https://tinkoff.github.io/investAPI/stoporders/#stopordertype

**Comment by vodolaz095** [comment]
как я понял, вопросы были больше по InvestAPI, а не по моей библиотеке, которая сгенерирована из официальных контрактов. поэтому, я закрываю вопрос.
