### ISSUE TITLE
пропуск события my trades

### ISSUE THREAD

**Issue by goupdate** [vodolaz095/go-investAPI#6]
Приветствую снова.

Периодически код использования библиотеки пропускает событие прихода своих сделок
```

func (b *Broker) listenMyTrades(tradesChan chan<- *models.OrderTrades) {
	defer zipologger.HandlePanic()
	request := investapi.TradesStreamRequest{
		Accounts: []string{b.accountId},
	}

	for {
		func() {
			b.CleanCache()

			commonRateLimiter.Wait()
			feed := investapi.NewOrdersStreamServiceClient(b.client.Connection)
			stream, err := feed.TradesStream(context.TODO(), &request)
			if err != nil {
				detailErrorInfo(err, error_log)
				conn_err_log.Printf("%s : while subscribing to trades feed", err)
				time.Sleep(time.Second * 2)
				return
			}
			defer stream.CloseSend()

			for {
				msg, err := stream.Recv()
				if err != nil {
					conn_err_log.Printf("%s : while receiving trades data", err)
					time.Sleep(time.Second * 2)
					break
				}
				if msg != nil {
					trade := msg.GetOrderTrades()
					if trade != nil {
						var trades []*models.OrderTrade
						for _, t := range trade.GetTrades() {
							trades = append(trades, &models.OrderTrade{
								When:     t.DateTime.AsTime(),
								Price:    t.GetPrice().ToFloat64(),
								Quantity: t.GetQuantity(),
							})
						}

						var dir = models.OrderDirection_BUY
						switch trade.GetDirection() {
						case investapi.OrderDirection_ORDER_DIRECTION_BUY:
							dir = models.OrderDirection_BUY
						case investapi.OrderDirection_ORDER_DIRECTION_SELL:
							dir = models.OrderDirection_SELL
						}

						tr := &models.OrderTrades{
							OrderId:   trade.OrderId,
							CreatedAt: trade.CreatedAt.AsTime(),
							Direction: dir,
							Trades:    trades,
						}

						log_trades.Printf("MY TRADE: %s", tr.String())

						if b.onTradeEvent != nil {
							b.onTradeEvent(tr)
						}

						tradesChan <- tr
					}
				}
				time.Sleep(10 * time.Millisecond)
			}
		}()
	}
}
```

**Comment by vodolaz095** [comment]
скорее всего это лимиты - у меня был аналогичный случай, когда хотел получать стоимость крайних сделок - аналогично на одно соединение приходили сообщение, а на другое - не приходили.

https://github.com/vodolaz095/stocks_broadcaster#%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F

я бы попробывал сделать несколько соединений с разных исходящих IP адресов для подписок

**Comment by vodolaz095** [comment]
вообще код выглядит, как будто бы в одном треде всё выполняется.
Теоритически так может терять сообщения - пока первое обрабатывается, второе уже пришло, но не получилось его обработать.

я бы добавил больше логов уровня отладки, и сделал бы всё в нескольких горутинах, связанных одним буферизированным каналом, как я понял, это `tradesChan <- tr`

горутины первого типа получают сообщения, а второго типа - уже обрабатывают

```go
 tradesChan := make(chan something, 100)

go func(){ // reader
stream, err := feed.TradesStream(context.TODO(), &request)
...
for {
		msg, err := stream.Recv()
                ...
                tradesChan <- msg
}
}()

go func(){ // processor
  for event := range tradesChan {

}
}

```

как в таком примере - https://gobyexample.com/worker-pools

я так реализовал ридер
https://github.com/vodolaz095/stocks_broadcaster/blob/master/internal/transport/reader/invest_api/reader.go

он как минимум подписок 1000 держит на среднем vps c 8 IP адресами

**Comment by goupdate** [comment]
Да, отличная мысль с буфером, так и поступаю: буфер 200, даже путем пропуска избыточных данных:
```
if len(candlesChan) < 2 {
     candlesChan <- c
}
```
Однако это не помогает, даже буферизация, добавлю логи длины буфера, вдруг действительно кто-то не успевает читать, но не думаю что дело в этом, будто обрывается связь или брокер не досылает сделки.

**Также:**
Предлагаю объединиться в библиотеке-обертке над go-investAPI.
Т.к. здесь находится ее первоисточник, то здесь же можно расположить и продолжение-развитие проекта, прикладываю его временно как вложение, затем удалю. Некоторые апи в broker.go недоразвиты т.к. за 3 года так и не были использованы в основном проекте.

**Comment by vodolaz095** [comment]
> Предлагаю объединиться в библиотеке-обертке над go-investAPI.

если Вы сделаете какой-нибудь форк\PR - я не против, но на данный момент я ничего нового в библиотеку добавлять не хочу - она как раз и нужна мне как низкоуровневый API, в котором нет ничего лишнего, и всё на усмотрние пользователей.

всё более высокоуровневое надо, имхо, делать в отдельных библиотеках.

хотя, я готов рассмотреть варианты, когда за пожертвование на развитие проекта я могу сделать какие-либо новые фичи
